unique_ids:
  forms:
    colorpicker: '1695617721532398218535154.59485'
    Barnsley_Fern: '1648703992529347091533905.973'
    Hypocycloide: 77VFKRJ5PJHXOJT5VQY6AMYRBQFSR2JR
    Nieuwe_wereld: 67ESWFHX4BJVDFEQ7ND6FIQWXXLMBLBX
    Eenvoudige_Fractals: N7LT5Q7SKL47DUDJI5ZRVUYXXIUJIRPC
    Wiskunde: PCBVUYEFFLFUPASJPJ53MPZJBP6WPU6G
    Kat_en_muis: AYSXJCSHKDCIKSARLCWI43ZHYN3SPA2L
    Spiraal_van_Archimedes: N26CWNOVZVQTHDWZIJA3YI2XJCQ55VPB
    Leven: L546KH62MU3C677S4ZU6TWOCA7IOLV2B
    Margaret_Kepner: '1695127441321744447572671.5809'
    Boom_van_Pythagoras: OZDYJPLRDPG4D6SGFMH53PDDO6TJEB57
    Lissajous: POFVNMUZ7WSXGEK6XZIS7OTDCJZXCI2Y
    peanolijn: D5RQ375DCHJK7RZ4QNBRBBKR3TVVYWC3
    Cycloide: 7SBQMRRME6CCQQUZD3KG6SAZGE6HV7TY
    Eenvoudige_Fractals.uitleg: BHLDQEMKMB74KR5YYM6BDVUKVLY2ZA4V
  modules: {}
  server_modules:
    ServerModule1: '1648711159559300182938961.71497'
  assets:
    standard-page.html: WZGBSCPEPEIOIGROOC75G3I6UZ4HK62Y
    theme.css: QAQEZ2WKSYIORT4O4JZQK6UZWF6LZP6R
