unique_ids:
  forms: {Canvas: AMKLGDQPC5UAYZGRLAU5RE72UA2JO4KJ, Hypocycloide: 77VFKRJ5PJHXOJT5VQY6AMYRBQFSR2JR,
    Krommen: PCBVUYEFFLFUPASJPJ53MPZJBP6WPU6G, Lissajous: POFVNMUZ7WSXGEK6XZIS7OTDCJZXCI2Y,
    Spiraal_van_Archimedes: LA3RLFC6ALPLH4ID5TU2OZTIBWY5FU4K}
  modules: {}
  server_modules: {}
  assets: {standard-page.html: WZGBSCPEPEIOIGROOC75G3I6UZ4HK62Y, theme.css: QAQEZ2WKSYIORT4O4JZQK6UZWF6LZP6R}
