unique_ids:
  forms: {Canvas: AYSXJCSHKDCIKSARLCWI43ZHYN3SPA2L, Hypocycloide: 77VFKRJ5PJHXOJT5VQY6AMYRBQFSR2JR,
    Cycloide: 7SBQMRRME6CCQQUZD3KG6SAZGE6HV7TY, Krommen: PCBVUYEFFLFUPASJPJ53MPZJBP6WPU6G,
    Lissajous: POFVNMUZ7WSXGEK6XZIS7OTDCJZXCI2Y, Spiraal_van_Archimedes: N26CWNOVZVQTHDWZIJA3YI2XJCQ55VPB}
  modules: {}
  server_modules: {}
  assets: {standard-page.html: WZGBSCPEPEIOIGROOC75G3I6UZ4HK62Y, theme.css: QAQEZ2WKSYIORT4O4JZQK6UZWF6LZP6R}
