unique_ids:
  forms: {Form1: KBH6K3OZSCLNRNDEV24LD7FLMT5IOFO7, Hypocycloide: 77VFKRJ5PJHXOJT5VQY6AMYRBQFSR2JR,
    Krommen: PCBVUYEFFLFUPASJPJ53MPZJBP6WPU6G, Lissajous: POFVNMUZ7WSXGEK6XZIS7OTDCJZXCI2Y}
  modules: {}
  server_modules: {}
  assets: {standard-page.html: WZGBSCPEPEIOIGROOC75G3I6UZ4HK62Y, theme.css: QAQEZ2WKSYIORT4O4JZQK6UZWF6LZP6R}
